### ISSUE TITLE
gmp_klee_inv_arg.x86_64 crashes KLEE by calling `raise()`

### ISSUE THREAD

**Issue by delcypher** [danielschemmel/fp-benchmarks-aachen#4]
@danielschemmel @afd @ccadar

The `gmp_klee_inv_arg.x86_64` benchmark crashes our fork of KLEE because libgmp's error handler tries to call `raise(SIGFPE)`. Our version of KLEE just calls this as an external which causes KLEE is effectively call `kill()` on itself.

The spec file currently contains

```
  klee_inv_arg:
    defines:
      KLEE: null
      INVALID_ARGUMENTS: null
    dependencies:
      klee_runtime: {}
    description: >
      Tests if gmp correctly rejects invalid arguments. >
      This should never reach the assert in the main function.
    verification_tasks:
      no_assert_fail:
        correct: true
      no_reach_error_function:
        correct: false
        counter_examples:
          -
            description: 'Expected Error'
            locations:
              -
                description: 'first method of abortion'
                file: 'gmp-6.1.1/invalid.c'
                line: 84
```

The expected failure is on [line 84](https://github.com/danielschemmel/fp-benchmarks-aachen/blob/f0e03d3f598dcc1643d91a4014ddc3f27564f8ba/real/gmp/gmp-6.1.1/invalid.c#L84) which is a call to `abort()`. Notice before that call is `raise(SIGFPE)`.

``` c
void
__gmp_invalid_operation (void)
{
  raise (SIGFPE);
  abort ();
}
```

@danielschemmel I'm not sure how you to chose to handle `raise()` but the fact you put the `abort()` as the failure sounds like you are treated it as a no-op which isn't correct. KLEE doesn't currently have proper support for modelling signals so handling `raise()` properly is a bit out of scope.

How do you want to handle this? The simplest thing is to remove the `raise(SIGFPE)`
